### ISSUE TITLE
Unable to re-authenticate Coway Integration

### ISSUE THREAD

**Issue by itzalgd24** [RobertD502/home-assistant-iocare#46] opened 2024-05-21 16:00 UTC
Recently getting multiple re-auth errors for the integration. Have been able to re-auth with no issues until today. Now getting the following errors:

This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/coway/config_flow.py:68
integration: Coway IoCare (documentation, issues)
First occurred: 7:37:51 AM (10 occurrences)
Last logged: 11:56:16 AM

/config/custom_components/coway/config_flow.py:68: RuntimeWarning: coroutine 'ClientResponse.text' was never awaited errors["base"] = "cannot_connect"

AND:

This error originated from a custom integration.

Logger: custom_components.coway
Source: custom_components/coway/util.py:36
integration: Coway IoCare (documentation, issues)
First occurred: 7:37:51 AM (10 occurrences)
Last logged: 11:56:16 AM

Failed to get information from Coway servers: Coway API error while fetching login page: <coroutine object ClientResponse.text at 0x7f3a3c55f680>
Failed to get information from Coway servers: Coway API error while fetching login page: <coroutine object ClientResponse.text at 0x7f3a3a055540>
Failed to get information from Coway servers: Coway API error while fetching login page: <coroutine object ClientResponse.text at 0x7f3a387ab3e0>
Failed to get information from Coway servers: Coway API error while fetching login page: <coroutine object ClientResponse.text at 0x7f3a302b2260>
Failed to get information from Coway servers: Coway API error while fetching login page: <coroutine object ClientResponse.text at 0x7f3a566e8820>

Running HAOS 2024.5.4

**Comment by RobertD502** [comment] 2024-05-21 16:06
duplicate of #45

**Closed by RobertD502** 2024-05-21 16:06 UTC
