### ISSUE TITLE
Retrying Setup: List Index is Out Of Range

### ISSUE THREAD

**Issue by cmaglio** [RobertD502/home-assistant-iocare#16] opened 2022-11-24 01:22 UTC
Hello! Thanks for your hard work on this integration. I found the other old repo which doesn't work with the new Coway logins... and that led me here. It then took me a bit to realize I needed to migrate the old Coway account to a new Coway account before this integration would work. I finally got that all figured out and now the setup wizard works, the login is authorized, and the integration starts its setup. Problem is, I am getting an error on the Integration card after the wizard:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/37604281/203673236-3e030698-7f4d-4164-aa23-9eb1fd2d6cb8.png">

Any idea what might be going on here?

Thanks for any help you can provide!

**Comment by RobertD502** [comment] 2022-11-24 01:23
Did you make sure to delete the old integration before installing this one / deleting your browser cache?

**Comment by cmaglio** [comment] 2022-11-24 01:25
Yes, I deleted it, restarted HA twice, and cleared my browser cache. I have two of the 400S model air filters by the way.

**Comment by RobertD502** [comment] 2022-11-24 01:26
Do you happen to use discord? I'll have to see why your account is doing that so I'll need temporary access.

**Comment by cmaglio** [comment] 2022-11-24 01:33
Yep: Bosston#4561

No problem, I have a temporary password set up if you need to use the account.

**Comment by RobertD502** [comment] 2022-11-24 05:06
Fixed in `Version 0.1.6`. 

`Caused by:` Purifier not connected to WiFi.

`Note:` Only the purifier that is connected to WiFi will show up in Home Assistant. Once you get the other purifier connected again, Home Assistant will be able to pull it in as well.

**Closed by RobertD502** 2022-11-24 05:06 UTC
