### ISSUE TITLE
Coway API error with Airmega 250s

### ISSUE THREAD

**Issue by tymm** [RobertD502/home-assistant-iocare#34] opened 2024-03-09 12:20 UTC
Hey,

Thank you for this great integration.

When I'm trying to connect my new Airmega 250s, I get the following error:
"Failed setup, will retry" and "Coway API error: Coway server failed to return purifier quality status".

**Comment by RobertD502** [comment] 2024-03-09 17:48
Are there any logs that you can share?

The "failed to return purifier data" just means that the coway servers returned an error when calling the purifier endpoint. This can happen intermittently.

**Comment by tymm** [comment] 2024-03-09 20:21
I turned on debug logging for the integration but the only logs that I can offer are the following from the docker container output.

```
2024-03-09 21:11:34.394 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 6.052 seconds (success: False)
2024-03-09 21:13:08.992 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 17.346 seconds (success: False)
2024-03-09 21:13:22.649 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 8.545 seconds (success: False)
2024-03-09 21:13:37.324 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 4.582 seconds (success: False)
2024-03-09 21:14:10.821 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 13.086 seconds (success: False)
2024-03-09 21:14:59.465 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 8.521 seconds (success: False)
2024-03-09 21:16:25.902 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 6.367 seconds (success: False)
2024-03-09 21:16:52.579 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 6.200 seconds (success: False)
2024-03-09 21:17:02.086 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 4.027 seconds (success: False)
2024-03-09 21:17:16.524 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 4.189 seconds (success: False)
2024-03-09 21:17:42.970 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 6.356 seconds (success: False)
2024-03-09 21:19:23.485 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 8.208 seconds (success: False)
2024-03-09 21:19:35.091 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 6.356 seconds (success: False)
```

**Comment by kenblu24** [comment] 2024-03-13 22:43
I have had the same issue for a couple months now. Was waiting till I had time to properly document the issue, but since you posted this, I'll hop on board.

Procedure:
Taken from a running system. I click on "Enable debug logging" in the supervisor for the coway custom component, reload the component, wait to go from "Initializing" to "Failed setup, will retry", and turn off debug logging.


This appears in the resulting log in what appears to be the system startup logs:
'''2024-03-12 11:44:47.626 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: coway'''
This appears in the log at the end:
```
2024-03-13 18:38:46.718 WARNING (MainThread) [homeassistant.components.rest.util] JSON result was not a dictionary or list with 0th element a dictionary
2024-03-13 18:38:55.570 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 25.035 seconds (success: False)
2024-03-13 18:39:01.725 WARNING (MainThread) [homeassistant.components.rest.util] JSON result was not a dictionary or list with 0th element a dictionary
2024-03-13 18:39:16.720 WARNING (MainThread) [homeassistant.components.rest.util] JSON result was not a dictionary or list with 0th element a dictionary
2024-03-13 18:39:31.559 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 30.603 seconds (success: False)
2024-03-13 18:39:31.725 WARNING (MainThread) [homeassistant.components.rest.util] JSON result was not a dictionary or list with 0th element a dictionary```

**Comment by Landshark77** [comment] 2024-03-14 17:47
Recently received my 400S and I'm having the exact same issue as above.  Everything so far is working fine in the Mobile app.  If there's any other data I can provide that's not already mentioned above, just give me a shout.  Happy to help where I can.

**Comment by RobertD502** [comment] 2024-03-18 15:08
On vacation so I won't be able to do anything until I'm back. Looks like they have made some changes to the API as indicated by the forced requirement to update the mobile app to continue using:

![image](https://github.com/RobertD502/home-assistant-iocare/assets/52541649/d31ab641-f09d-46c5-9296-f7d926745799)

**Comment by RobertD502** [comment] 2024-03-18 23:53
I have investigated the cause of the current issue and it is due to Coway completely changing the API. This will require a completely rewrite of the backend library, which I'll get to once I have some time. I will add a message to the readme of this repo to indicate the state - this message will be removed when the rewrite has been completed.

**Comment by ZappavdV** [comment] 2024-04-17 17:47
Hi,

I bought a 300s unit last week and I had the same issue until now.

I disabled the 'skip password change' and like magic, everything seems to work. Maybe this can work for other people too?

Cheers!

**Comment by kenblu24** [comment] 2024-04-17 17:50
@ZappavdV Lucky you. Perhaps your device is old enough that your Coway app and account are pinned at an old version?

**Comment by RobertD502** [comment] 2024-04-22 19:55
> Hi,
> 
> I bought a 300s unit last week and I had the same issue until now.
> 
> I disabled the 'skip password change' and like magic, everything seems to work. Maybe this can work for other people too?
> 
> Cheers!

The most likely reason this was your issue, and it was resolved by changing this option, is because your Coway account is brand new - With your account being new, Coway won't present you with the password change prompt during login. Possibly, at some point, Coway will start serving you with a prompt to change your password. At that time, the integration will fail to work, and you'll need to adjust the integration's options to have the "skip password change" option enabled.

For anyone that is experiencing issues with purifiers working and then the integration not working when a `newly purchased purifier is added to the account`, I'll need to investigate if Coway is doing something different with a new firmware version on the purifiers  / what happens in the backend library to cause the integration to break. The only way I can investigate this is by having anyone with such an issue reach out to me on Discord (RobertD502) to temporarily grant me access to their Coway account.

@kenblu24 It looks like something funky is going on with your account....Just like the scenario above, the easiest way to get to the bottom of this is to grant me temp access to your account (to debug what is going on) by reaching out to me on Discord (RobertD502).

**Comment by randomstring** [comment] 2024-04-26 19:11
> For anyone that is experiencing issues with purifiers working and then the integration not working when a `newly purchased purifier is added to the account`, I'll need to investigate if Coway is doing something different with a new firmware version on the purifiers / what happens in the backend library to cause the integration to break. The only way I can investigate this is by having anyone with such an issue reach out to me on Discord (RobertD502) to temporarily grant me access to their Coway account.

This is exactly my situation. Integration worked great right up until I added a new 250S to my account a few days ago.

@RobertD502  Is there a way I can provide debugging info without sharing account credentials?

**Comment by RobertD502** [comment] 2024-04-27 17:40
Unfortunately, I won't be able to get far with just a debug from the backend library - I'd need to use an affected account with an older version of the IoCare app (to use the older API) and MITM the connection in order to see what it is doing. For anyone concerned, you can change your password after I am done. I don't have any nefarious intentions (I have users provide accounts all the time for adding new devices for my other integrations).

The only other solution is for any affected user to do the work themselves and then open a PR that fixes the issue in the cowayaio backend library.

**Comment by randomstring** [comment] 2024-04-27 18:07
As a test, I removed the new 250S from my account (via the iPhone app) and reloaded the Homeassistant integration and it initialized correctly and I had access to the previous 400S again. Re-registered the 250S and reloaded the integration and it fails again.

Deleting the older 400S and leaving the newer 250S and then restarting the HomeAssistant integrations fails. Adding the older 400s back also continues to fail.

@RobertD502 I'm pinging you on discord about credentials.

**Comment by pflonk** [comment] 2024-04-27 21:28
@RobertD502 if it helps, I made an account with Coway on 9th of april, so quite recently, and use an AP-1512HHS. 
If you need credentials, tell me about the best way to send them to you. 😃

**Closed** 2024-04-28 23:05 UTC

**Comment by RobertD502** [comment] 2024-04-28 23:27
`0.4.0` has been released which should take care of the issue caused by newer purifiers not using the old quality status endpoint.

Thank you to @randomstring for giving me temporary access to his account which allowed me to track down this issue and add some extra goodies for 250S users.

**Comment by Landshark77** [comment] 2024-04-28 23:40
I can confirm this works with my new 400S.  Many thanks!

**Comment by pflonk** [comment] 2024-04-28 23:57
Can confirm as well, works with my AP-1512HHS.
Thanks a lot for this fix 👌😀

**Comment by gh69** [comment] 2024-04-29 07:18
My previously not-working 250S is now working as well.  @RobertD502 Thank you!

**Comment by tymm** [comment] 2024-05-20 11:18
> My previously not-working 250S is now working as well. @RobertD502 Thank you!

Same here.
