### ISSUE TITLE
Setup fails with "Check the logs"

### ISSUE THREAD

**Issue by kenblu24** [RobertD502/home-assistant-iocare#42] opened 2024-04-30 14:59 UTC
`async_get_purifiers_data()` succeeds just fine for me now (I previously had an error getting the MCU data).

However, the integration still fails setup. 

![image](https://github.com/RobertD502/home-assistant-iocare/assets/7890808/17f99c95-290e-4833-85e8-b3a4b8cc81ba)

"Enable Debug Logging" log:
```
<file start>
2024-04-30 10:40:50.376 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration coway which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-30 10:40:50.378 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-30 10:40:50.380 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dyson_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-30 10:40:50.382 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-30 10:40:54.212 WARNING (MainThread) [homeassistant.components.rest.util] JSON result was not a dictionary or list with 0th element a dictionary
2024-04-30 10:41:09.337 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-04-30 10:41:09.818 ERROR (MainThread) [androidtvremote2] Device doesn't support sending keys. Try clearing the storage of the Android TV Remove Service system app. On the Android TV device, go to Settings > Apps > See all apps > Show system apps. Then, select Android TV Remote Service > Storage > Clear data/storage.
2024-04-30 10:41:10.027 WARNING (MainThread) [homeassistant.components.rest.util] JSON result was not a dictionary or list with 0th element a dictionary
2024-04-30 10:41:36.900 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 27.734 seconds (success: False)
2024-04-30 10:42:01.899 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 24.559 seconds (success: False)
2024-04-30 10:42:35.899 DEBUG (MainThread) [custom_components.coway] Finished fetching coway data in 23.814 seconds (success: False)
<truncated>
```

**Comment by RobertD502** [comment] 2024-04-30 16:00
@kenblu24 Just looked at the data you included in the cowayaio issue opened yesterday. Your purifier has a net status of false, which indicates the coway servers are listing the purifier as being offline. Please physically disable wifi on the purifier and then enable it again. That should get the purifier to ping Coway's servers to let them know the purifier is online.

**Comment by dd143999** [comment] 2024-04-30 16:01
Another(!) app version just hit the App Store (yes, since the work you did to get things working again yesterday).  I haven't updated it yet, because that seems to trigger things on the account/device level that force API changes that break things until you're able to intercept the current state of things and figure out which piece of the puzzle was changed, and 0.4.1 is currently working for me.  Looks like Coway is still "actively" "developing" things on their end.

**Comment by RobertD502** [comment] 2024-04-30 16:08
> Another(!) app version just hit the App Store (yes, since the work you did to get things working again yesterday). I haven't updated it yet, because that seems to trigger things on the account/device level that force API changes that break things until you're able to intercept the current state of things and figure out which piece of the puzzle was changed, and 0.4.1 is currently working for me. Looks like Coway is still "actively" "developing" things on their end.

Yup, noticed that this morning. You are fine to update the app. Can confirm the integration continues to work after using the latest IoCare app.

**Comment by RobertD502** [comment] 2024-05-20 16:36
Integration tested and working with user's credentials on my HA system pointing to the cause being specific to user environment. Closing for now.

**Closed by RobertD502** 2024-05-20 16:36 UTC

**Comment by kenblu24** [comment] 2024-05-30 16:34
Solved! Kind of. 

Issue was fixed by disabling IPV6 on the network interface for my HA machine, as well as disabling IPV6 in my router/firewall. 

I'm not sure what was happening, but I think some odd IPV6 routing was happening. Either my ISP turned on IPV6, or wireguard was doing things despite being disabled. This may have had an effect on some SSL certificates as well. A few days ago, [nearly all of my cloud integrations failed](https://community.home-assistant.io/t/multiple-cloud-integrations-fail-but-not-all/734013/2), and disabling IPv6 fixed almost all of them, including this integration. 

Thanks again to Robert for offering his time to try and solve my problem, and of course for making this wonderful integration and dealing with Coway's numerous API changes.

**Comment by RobertD502** [comment] 2024-06-01 21:39
Thanks for reporting back! It also ended up being the cause and resolution for another user.
